spring.application.name=Smart-Route-Planner

server.port=8080

# Logging
logging.level.org.springframework.web=INFO
logging.level.com.SmartMaps.Smart.Route.Planner=DEBUG

# WebClient timeout (optional)
spring.webflux.base-path=/

# Jackson
spring.jackson.default-property-inclusion=non_null

# DevTools
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# OpenStreetMap APIs
osm.nominatim.url=https://nominatim.openstreetmap.org

osm.overpass.url=https://overpass-api.de/api

# Server Error Messages
server.error.include-message=always
server.error.include-binding-errors=always